### ISSUE TITLE
Multiple bugs in z plan and channel widgets

### ISSUE THREAD

**Issue by adamkglaser** [AllenNeuralDynamics/view#45] opened 2024-06-18 03:43 UTC
Is your feature request related to a problem? Please describe.
- Range and above/below z plan widgets seem reversed, the max value goes to z [mm] and the min values goes to z max [mm]
- The step size and steps rows seem to be buggy in the channel plan widget.
- I can't seem to enter numbers for any row other than the first row
- (I think) the first row should auto populate all rows? This doesn't seem to happen, they are all always 0's for rows >1.
- Step size and steps column seem to be capped at 2 digits? For example I can't make step size 100 um even if the z / zmax are >100 um.
- Once a channel is added to the channel plan widget, and then removed with X, it disappears forever.

Describe the solution you'd like
A lot of these breaks may be due to multiple setting dependences of items in these two tables. For example zmax is settable in the table, but it is also being set by the zplan widget.
- I would suggest making zmax an indicator only, and it can only be set from the z plan widget above.
- Step size is settable in the channel plan widget. Steps is only an indicator. Step size is auto-adjusted so that steps is an integer based on (zmax - z).

Acceptance Criteria
- [ ] Range and above/below z plan widget are reversed and map to z / zmax correctly
- [ ] zmax is an indicator, z and zmax are only set by the z plan widget
- [ ] Step size can be entered in all rows
- [ ] Step size from row 1 when entered auto populates all rows below
- [ ] Steps is an indicator that shows number of steps for (zmax - z) / step size
- [ ] Steps is enforced to be an integer (auto adjust step size to enforce this)
- [ ]  When channels are X'd out of the channel plan widget, they go back into the available list of channels to add
- [ ] All settable values in tables are not restricted in numbers that can be entered (unless it is limited by a delineated property min/max). Right now it seems it is not possible to enter >2 digits from the keyboard for some of the cells in the table

**Comment by micahwoodard** [comment] 2024-06-18 15:30
@adamkglaser 
- Range and above/below z plan widgets seem reversed, the max value goes to z [mm] and the min values goes to z max [mm]
    - Yeah looking at this, I got confused. I was thinking that z in the table was the start of a tile and z max was the end of the tile. I can fix this
- The step size and steps rows seem to be buggy in the channel plan widget.
    -  Buggy how so? I don't see it on my end but I'm probably not doing exactly what you're doing
- I can't seem to enter numbers for any row other than the first row
    -  In what table? I'm guessing the z plan table. That's by design since it doesn't make sense to me to allow the user to edit the row, column, x, and y coordinates directly. The z should only be editable if the grid is anchored in z, which is a checkbox in the scan plan widget. Otherwise it will follow where ever the fov is. The last column z max should be the only one that can be edited initially
- (I think) the first row should auto populate all rows? This doesn't seem to happen, they are all always 0's for rows >1.  
    - Yeah I agree that should be the right behavior. Are you seeing it in both tables? I'm kinda seeing behavior in the z plan table when using the range or above/below settings. 
- Step size and steps column seem to be capped at 2 digits? For example I can't make step size 100 um even if the z / zmax are >100 um.
    - Yeah I've fixed that in another issue that will be merged in shortly
-  Once a channel is added to the channel plan widget, and then removed with X, it disappears forever.
   - I see your point here

**Comment by adamkglaser** [comment] 2024-06-18 16:38
Yes lets discuss this later this morning (I think the bugs are small, I can try to explain/reproduce).

**Comment by micahwoodard** [comment] 2024-06-18 18:02
@micahwoodard  Also QSpinItemDelegate not allowing to scroll to negative numbers

**Closed** 2024-07-01 21:06 UTC
